server:
  port: ${oauth2.port}
spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_auth
    username: root
    password: my-secret-pw
  application:
    name: easy-oauth2-server
  jmx:
    default-domain: easy-oauth2-server
  security:
    user:
      password: "{noop}secret10"
security:
  oauth2:
    client:
      id: local
      client-id: myclient
      client-secret: mysecret
      scope: dataflow.view,dataflow.manage,dataflow.create
      registered-redirect-uri:
        - http://localhost:9393/login
      auto-approve-scopes: '.*'
      authorized-grant-types:
        - authorization_code
        - client_credentials
        - password
    authorization:
      checkTokenAccess: isAuthenticated()
  authentication:
    file:
      enabled: true
      users:
        user: "{noop}password, ROLE_DATAFLOW.VIEW"
        admin: "{noop}nimda, ROLE_DATAFLOW.VIEW, ROLE_DATAFLOW.MANAGE, ROLE_DATAFLOW.CREATE, ROLE_DATAFLOW.SCHEDULE, ROLE_DATAFLOW.MODIFY, ROLE_DATAFLOW.DEPLOY, ROLE_DATAFLOW.DESTROY"
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
